package com.jdbc;

import com.zaxxer.hikari.HikariDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
            import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;

public class Application {

    public static void main(String[] args) {

        DataSource dataSource = createDataSource();

        try (Connection connection = dataSource.getConnection()) {

            try (PreparedStatement stmt = connection.prepareStatement(
                    "INSERT INTO USERS (FIRST_NAME, LAST_NAME, REGISTRATION_DATE) VALUES (?, ?, ?)"
                    , Statement.RETURN_GENERATED_KEYS)) { // return the auto-generated keys

                stmt.setString(1, "John");
                stmt.setString(2, "Doe");
                stmt.setObject(3, LocalDateTime.now());

                int insertedRows = stmt.executeUpdate();
                final ResultSet keysResultSet = stmt.getGeneratedKeys();
                keysResultSet.next();
                final long autogeneratedId = keysResultSet.getLong(1);// get the auto-generated key value

                System.out.println("Inserted [" + insertedRows + "] row into table" +
                        " users, with autogenerated id [" + autogeneratedId + "]");
            }

            System.out.println("connection.isValid(0) = "
                    + connection.isValid(0));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private static DataSource createDataSource() {
        HikariDataSource dataSource = new HikariDataSource();
        dataSource.setJdbcUrl("jdbc:h2:~/mydatabase;INIT=RUNSCRIPT FROM 'classpath:schema.sql'");
        dataSource.setUsername("sa");
        dataSource.setPassword("somePassword");
        return dataSource;
    }
}
